### ISSUE TITLE
Ultrahook setup failing

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-planning#15]
When configuring ultrahook as per these instructions:
http://appdev.openshift.io/getting-started.html#_optional_trigger_builds_automatically_with_ultrahook

I get the following error on first update commit:
```
$ ultrahook -k MY_AWESOME_KEY github https://192.168.64.2:8443/oapi/v1/namespaces/demo4241/buildconfigs/demo4241/webhooks/1493057664733/github
Authenticated as AN_AWESOME_PERSON
Forwarding activated...
http://github.AN_AWESOME_PERSON.ultrahook.com -> https://192.168.64.2:8443/oapi/v1/namespaces/demo4241/buildconfigs/demo4241/webhooks/1493057664733/github
Forwarding activated...
http://github.AN_AWESOME_PERSON.ultrahook.com -> https://192.168.64.2:8443/oapi/v1/namespaces/demo4241/buildconfigs/demo4241/webhooks/1493057664733/github
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (OpenSSL::SSL::SSLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1396:in `send_entity'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1184:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/ultrahook-0.1.4/lib/ultrahook/client.rb:127:in `http_post'
	from /Library/Ruby/Gems/2.0.0/gems/ultrahook-0.1.4/lib/ultrahook/client.rb:116:in `process_request'
	from /Library/Ruby/Gems/2.0.0/gems/ultrahook-0.1.4/lib/ultrahook/client.rb:90:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/ultrahook-0.1.4/lib/ultrahook/client.rb:160:in `block (3 levels) in init_stream'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:411:in `call_block'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:402:in `<<'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:106:in `read'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:313:in `read_chunked'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:276:in `block in read_body_0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:269:in `inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
	from /Library/Ruby/Gems/2.0.0/gems/ultrahook-0.1.4/lib/ultrahook/client.rb:155:in `block (2 levels) in init_stream'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/ultrahook-0.1.4/lib/ultrahook/client.rb:153:in `block in init_stream'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/ultrahook-0.1.4/lib/ultrahook/client.rb:148:in `init_stream'
	from /Library/Ruby/Gems/2.0.0/gems/ultrahook-0.1.4/lib/ultrahook/client.rb:65:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/ultrahook-0.1.4/bin/ultrahook:6:in `<top (required)>'
	from /usr/local/bin/ultrahook:23:in `load'
	from /usr/local/bin/ultrahook:23:in `<main>'
```

On restart, and subsequent commits, it appears the pushes happen:
```
Forwarding activated...
http://github.AN_AWESOME_PERSON.ultrahook.com -> https://192.168.64.2:8443/oapi/v1/namespaces/demo4241/buildconfigs/demo4241/webhooks/1493057664733/github
Forwarding activated...
http://github.AN_AWESOME_PERSON.ultrahook.com -> https://192.168.64.2:8443/oapi/v1/namespaces/demo4241/buildconfigs/demo4241/webhooks/1493057664733/github
```

but no builds are triggered

**Comment by rhoads-zach** [comment]
@ALRubinger @gytis FYI

**Comment by quintesse** [comment]
Haven't been able to reproduce this yet, it seems to work fine here:

```
$ ultrahook github https://192.168.42.46:8443/oapi/v1/namespaces/demo/buildconfigs/demo/webhooks/1493122470715/github
Authenticated as AN_AWESOME_PERSON
Forwarding activated...
http://github.AN_AWESOME_PERSON.ultrahook.com -> https://192.168.42.46:8443/oapi/v1/namespaces/demo/buildconfigs/demo/webhooks/1493122470715/github
[2017-04-25 14:33:32] POST https://192.168.42.46:8443/oapi/v1/namespaces/demo/buildconfigs/demo/webhooks/1493122470715/github - 200
```

The only difference I see is that I don't use the `-k` flag for ultrahook (I don't think it's necessary?)

**Comment by rhoads-zach** [comment]
i've omitted the -k KEY aspect and am still getting the same error. 

When i try to post directly using a REST testing app, i'm getting a "certificate invalid" error. I'll see if i can do something about importing the certificate on macOS.

**Comment by rhoads-zach** [comment]
I've tried "always trusting" the cert, but its still failing.

**Comment by gastaldi** [comment]
Closing as out-of-date
