### ISSUE TITLE
BoosterCatalog no longer usable on premise or in minishift

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/appdev-planning#47]
seems something has happened in github lately so we can no longer initialise the booster forge addon. It takes forever to clone + index (see the log below).

We really need the BoosterCatalog created on disk in our docker image really so it just starts up immediately and doesn't spend many minutes cloning git + indexing things.

Here's the log - its taking over 4.5 minutes to index the catalog on minishift:
```
2017-07-31 16:27:58,619 INFO  [io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary] (io.fabric8.forge:fabric8-generator,1.0.36) Using jenkins workflow library: https://github.com/fabric8io/fabric8-jenkinsfile-library.git
2017-07-31 16:27:58,619 INFO  [io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary] (io.fabric8.forge:fabric8-generator,1.0.36) Using jenkins workflow library version: null
2017-07-31 16:27:58,626 INFO  [io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary] (io.fabric8.forge:fabric8-generator,1.0.36) Cloning git repo https://github.com/fabric8io/fabric8-jenkinsfile-library.git into directory /deployments/target/jenkinsfileLibrary cloneAllBranches: true
2017-07-31 16:27:58,649 INFO  [io.fabric8.project.support.GitUtils] (io.fabric8.forge:fabric8-generator,1.0.36) Using UsernamePasswordCredentialsProvider{user: , password length: 0}
2017-07-31 16:28:16,092 INFO  [io.fabric8.forge.generator.Fabric8GeneratorInitializer] (io.fabric8.forge:fabric8-generator,1.0.36) Using Jenkinsfile library at: target/jenkinsfileLibrary
2017-07-31 16:28:16,567 INFO  [org.obsidiantoaster.generator.rest.ObsidianResource] (ServerService Thread Pool -- 6) Warming up internal cache
2017-07-31 16:28:17,232 INFO  [org.infinispan.factories.GlobalComponentRegistry] (ServerService Thread Pool -- 6) ISPN000128: Infinispan version: Infinispan 'Ruppaner' 9.0.0.CR2
2017-07-31 16:28:17,323 INFO  [io.fabric8.forge.generator.cache.CacheFacade] (ServerService Thread Pool -- 6) starting caches
2017-07-31 16:28:18,436 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing contents from https://github.com/openshiftio/booster-catalog.git using next ref
2017-07-31 16:28:18,442 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Created /tmp/booster-catalog2565319995857371952
2017-07-31 16:28:31,555 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/health-check/wildfly-swarm/wildfly-swarm-health-check-booster.yaml ...
2017-07-31 16:28:36,784 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/health-check/spring-boot/spring-boot-health-check-booster.yaml ...
2017-07-31 16:28:47,545 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/health-check/vert.x/vertx-health-check-booster.yaml ...
2017-07-31 16:29:02,245 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/rest-http/wildfly-swarm/wildfly-swarm-rest-http-booster.yaml ...
2017-07-31 16:29:13,088 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/rest-http/spring-boot/spring-boot-rest-http-booster.yaml ...
2017-07-31 16:29:23,804 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/rest-http/vert.x/vertx-http-booster.yaml ...
2017-07-31 16:29:41,436 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/rest-http-secured/wildfly-swarm/wildfly-swarm-rest-http-secured-booster.yaml ...
2017-07-31 16:30:09,942 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/rest-http-secured/spring-boot/spring-boot-http-secured-booster.yaml ...
2017-07-31 16:31:18,668 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/rest-http-secured/vert.x/vertx-rest-http-secured-booster.yaml ...
2017-07-31 16:31:42,614 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/crud/wildfly-swarm/wildfly-swarm-rest-http-crud-booster.yaml ...
2017-07-31 16:32:00,689 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/crud/spring-boot/spring-boot-rest-http-crud-booster.yaml ...
2017-07-31 16:32:14,806 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/crud/vert.x/vertx-crud-booster.yaml ...
2017-07-31 16:32:29,897 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/circuit-breaker/wildfly-swarm/wildfly-swarm-circuit-breaker-booster.yaml ...
2017-07-31 16:32:31,383 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/circuit-breaker/spring-boot/spring-boot-circuit-breaker-booster.yaml ...
2017-07-31 16:32:43,600 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/circuit-breaker/vert.x/vertx-circuit-breaker-booster.yaml ...
2017-07-31 16:32:44,604 ERROR [org.jboss.as.controller.management-operation] (main) WFLYCTL0348: Timeout after [300] seconds waiting for service container stability. Operation will roll back. Step that first updated the service container was 'add' at address '[("deployment" => "generator.war")]'
2017-07-31 16:32:44,612 ERROR [org.jboss.as.server] (main) WFLYSRV0021: Deploy of deployment "generator.war" was rolled back with the following failure message: "WFLYCTL0344: Operation timed out awaiting service container stability"
2017-07-31 16:32:49,615 ERROR [org.jboss.as.controller.management-operation] (main) WFLYCTL0190: Step handler org.jboss.as.server.deployment.DeploymentHandlerUtil$1@9f674ac for operation {"operation" => "add","address" => ("deployment" => "generator.war"),"runtime-name" => "generator.war","enabled" => true,"persistent" => true,"operation-headers" => {"blocking-timeout" => 300},"content" => [{"hash" => bytes { 0x00 }}],"owner" => undefined} at address [("deployment" => "generator.war")] failed handling operation rollback -- java.util.concurrent.TimeoutException: java.util.concurrent.TimeoutException
	at org.jboss.as.controller.OperationContextImpl.waitForRemovals(OperationContextImpl.java:498)
	at org.jboss.as.controller.AbstractOperationContext$Step.handleResult(AbstractOperationContext.java:1369)
	at org.jboss.as.controller.AbstractOperationContext$Step.finalizeInternal(AbstractOperationContext.java:1328)
	at org.jboss.as.controller.AbstractOperationContext$Step.finalizeStep(AbstractOperationContext.java:1301)
	at org.jboss.as.controller.AbstractOperationContext$Step.access$300(AbstractOperationContext.java:1185)
	at org.jboss.as.controller.AbstractOperationContext.executeResultHandlerPhase(AbstractOperationContext.java:767)
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:644)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1322)
	at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:401)
	at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:209)
	at org.jboss.as.controller.ModelControllerImpl$3.execute(ModelControllerImpl.java:686)
	at org.jboss.as.controller.ModelControllerImpl$3.execute(ModelControllerImpl.java:676)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at org.jboss.as.controller.client.AutoCloseable$Closeable$ModelControllerClient$2000189194$Proxy$_$$_WeldClientProxy.execute(Unknown Source)
	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:288)
	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:100)
	at org.wildfly.swarm.container.runtime.RuntimeDeployer$Proxy$_$$_WeldClientProxy.deploy(Unknown Source)
	at org.wildfly.swarm.Swarm.deploy(Swarm.java:426)
	at org.wildfly.swarm.Swarm.main(Swarm.java:580)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:39)
	at org.wildfly.swarm.bootstrap.Main.run(Main.java:46)
	at org.wildfly.swarm.bootstrap.Main.main(Main.java:37)

2017-07-31 16:32:54,621 ERROR [org.jboss.as.controller.management-operation] (main) WFLYCTL0349: Timeout after [5] seconds waiting for service container stability while finalizing an operation. Process must be restarted. Step that first updated the service container was 'add' at address '[("deployment" => "generator.war")]'
2017-07-31 16:32:54,645 ERROR [stderr] (main) java.lang.reflect.InvocationTargetException
2017-07-31 16:32:54,646 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-07-31 16:32:54,647 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-07-31 16:32:54,649 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-07-31 16:32:54,649 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:498)
2017-07-31 16:32:54,650 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:39)
2017-07-31 16:32:54,651 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.run(Main.java:46)
2017-07-31 16:32:54,652 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:37)
2017-07-31 16:32:54,653 ERROR [stderr] (main) Caused by: org.wildfly.swarm.container.DeploymentException: org.wildfly.swarm.container.DeploymentException: WFSWARM0007: Deployment failed: WFLYCTL0344: Operation timed out awaiting service container stability
2017-07-31 16:32:54,653 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:302)
2017-07-31 16:32:54,653 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:100)
2017-07-31 16:32:54,654 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer$Proxy$_$$_WeldClientProxy.deploy(Unknown Source)
2017-07-31 16:32:54,655 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.deploy(Swarm.java:426)
2017-07-31 16:32:54,656 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:580)
2017-07-31 16:32:54,656 ERROR [stderr] (main) 	... 7 more
2017-07-31 16:32:54,657 ERROR [stderr] (main) Caused by: org.wildfly.swarm.container.DeploymentException: WFSWARM0007: Deployment failed: WFLYCTL0344: Operation timed out awaiting service container stability
2017-07-31 16:32:54,657 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:297)
2017-07-31 16:32:54,657 ERROR [stderr] (main) 	... 11 more
2017-07-31 16:32:54,658 ERROR [stderr] (main) Exception in thread "main" java.lang.reflect.InvocationTargetException
2017-07-31 16:32:54,658 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-07-31 16:32:54,659 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-07-31 16:32:54,659 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-07-31 16:32:54,659 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:498)
2017-07-31 16:32:54,659 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:39)
2017-07-31 16:32:54,660 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.run(Main.java:46)
2017-07-31 16:32:54,660 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:37)
2017-07-31 16:32:54,660 ERROR [stderr] (main) Caused by: org.wildfly.swarm.container.DeploymentException: org.wildfly.swarm.container.DeploymentException: WFSWARM0007: Deployment failed: WFLYCTL0344: Operation timed out awaiting service container stability
2017-07-31 16:32:54,661 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:302)
2017-07-31 16:32:54,661 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:100)
2017-07-31 16:32:54,661 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer$Proxy$_$$_WeldClientProxy.deploy(Unknown Source)
2017-07-31 16:32:54,661 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.deploy(Swarm.java:426)
2017-07-31 16:32:54,662 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:580)
2017-07-31 16:32:54,662 ERROR [stderr] (main) 	... 7 more
2017-07-31 16:32:54,662 ERROR [stderr] (main) Caused by: org.wildfly.swarm.container.DeploymentException: WFSWARM0007: Deployment failed: WFLYCTL0344: Operation timed out awaiting service container stability
2017-07-31 16:32:54,663 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:297)
2017-07-31 16:32:54,663 ERROR [stderr] (main) 	... 11 more
2017-07-31 16:33:00,420 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/configmap/wildfly-swarm/wildfly-swarm-configmap-booster.yaml ...
2017-07-31 16:33:07,088 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/configmap/spring-boot/spring-boot-configmap-booster.yaml ...
2017-07-31 16:33:13,555 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Indexing /tmp/booster-catalog2565319995857371952/configmap/vert.x/vertx-configmap-booster.yaml ...
2017-07-31 16:33:30,440 INFO  [io.openshift.launchpad.catalog.BoosterCatalogService] (ServerService Thread Pool -- 6) Finished content indexing
2017-07-31 16:33:31,306 INFO  [org.obsidiantoaster.generator.rest.ObsidianResource] (ServerService Thread Pool -- 6) Caches warmed up
2017-07-31 16:33:31,435 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 6) RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.obsidiantoaster.generator.rest.RestApplication$Proxy$_$$_WeldClientProxy
2017-07-31 16:33:31,436 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 6) RESTEASY002200: Adding class resource org.obsidiantoaster.generator.rest.ObsidianResource from Application class org.obsidiantoaster.generator.rest.RestApplication$Proxy$_$$_WeldClientProxy
2017-07-31 16:33:31,436 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 6) RESTEASY002200: Adding class resource org.obsidiantoaster.generator.rest.HealthResource from Application class org.obsidiantoaster.generator.rest.RestApplication$Proxy$_$$_WeldClientProxy
2017-07-31 16:33:31,436 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 6) RESTEASY002200: Adding class resource org.obsidiantoaster.generator.rest.OpenShiftServiceResource from Application class org.obsidiantoaster.generator.rest.RestApplication$Proxy$_$$_WeldClientProxy
2017-07-31 16:33:31,436 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 6) RESTEASY002210: Adding provider singleton org.obsidiantoaster.generator.rest.CorsFilter from Application class org.obsidiantoaster.generator.rest.RestApplication$Proxy$_$$_WeldClientProxy
2017-07-31 16:33:31,518 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 6) WFLYUT0021: Registered web context: /
2017-07-31 16:33:31,526 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 6) WFLYUT0022: Unregistered web context: /
2017-07-31 16:33:31,625 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0019: Host default-host stopping
2017-07-31 16:33:31,681 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0028: Stopped deployment generator.war (runtime-name: generator.war) in 47067ms
```

**Comment by gastaldi** [comment]
Peobably because of GitHub instabilities?https://status.github.com/messages

We're considering refactoring our booster-catalog-service to include the booster sources during build time, not runtime

**Comment by jstrachan** [comment]
this has been failing on and off for a week or so unfortunately. Including stuff at build time would be great!

**Comment by jstrachan** [comment]
@gastaldi any ideas how soon there might be a fix? 

Only we kinda need to merge the BoosterCatalog with our upstream quickstarts for upstream anyways; so its pretty tempting to just convert the booster catalog into a regular archetype catalog + populate the local maven repo with both the booster catalog source + our current upstream quickstarts then we're no longer dependent on the flaky github based git clones + indexing on startup. 

This would also help us have more control over what quickstarts we include and their version; making it easier to automate in our CI / CD process. Maybe thats gonna be simpler for the both of our teams?

**Comment by gastaldi** [comment]
I am not sure if using maven archetypes would be a good solution here. Need to check with the team on what would be an acceptable solution. But we definitely need to move away from the git cloning process while indexing, since we cannot rely on Github's availability.

I'll work on this this week and (hopefully) will have a solution before Friday.

**Comment by jstrachan** [comment]
Awesome many thanks!

**Comment by gastaldi** [comment]
Apparently the solution came early than expected: https://github.com/openshiftio/booster-catalog-service/pull/4 

Reviewing with the team now

**Comment by gastaldi** [comment]
Just had an idea: we could publish the whole booster-catalog content as a Docker image and (somehow) map as a Volume in the template. Then we could just specify the path where the contents are and boom! No Github anymore :)

WDYT?

**Comment by ALRubinger** [comment]
> Just had an idea: we could publish the whole booster-catalog content as a Docker image and (somehow) map as a Volume in the template. Then we could just specify the path where the contents are and boom! No Github anymore :)

How does that jive with Strachan's request to be able to update Boosters one by one?  While that solution seems pretty awesome in removing a remote dependency, it still ships all Boosters as a unified catalog.

**Comment by jstrachan** [comment]
I struggle to see how there can be one catalog with one set of boosters & versions of boosters for all platforms. The catalog then becomes a single monolith that must be tested on all possible platforms before it can ever be released.

A more microservice based approach sounds more optimal to me - letting boosters & platforms move faster with less blocking - where each platform maintains its own fork of the catalog (list of boosters & versions) which then gets updated for each platform when its been tested on that platform's CI tests.

Each platform can then bake its own catalog as a binary into its docker images
