### ISSUE TITLE
the new failsafe goals added to the vertx quickstarts break all the DevTools pipelines

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/appdev-planning#7]
its kinda scary quickstarts changing on the fly without any kind of versioning or heads up; makes it really hard to test anything works / doesn't work on DevTools as we just don't know, from hour by hour, whats gonna break.

Upstream in fabric8 we've always been really careful to release versions of quickstarts/wizards so that folks can test out new versions of wizards/quickstarts and if they work; upgrade and if not stay on older working versions. Then we use version change PRs with CI / CD to assert things can be used. Changing stuff in production at runtime is just scary!

FWIW on fabric8 upstream and on DevTools we run integration tests in a separate stage of the pipeline usually on a separate namespace reserved for testing (which is different from the default jenkins namespace).

The current failure is; the vertx projects worked on Friday; now they are broken without us changing any of our code.

As a first fix can we move the failsafe integration tests to another profile from 'openshift' so we can ignore them on DevTools.

Then would it be possible to have an obsidian-addon release which doesn't use git master of all the quickstarts so we can have some kind of confidence things might actually work on DevTools? e.g. switch each release of the addon to use a fixed sha/branch/tag of the quickstart git repos? Then feel free to use 'master' in your work if you are happy doing stuff like that - but folks who prefer to upgrade via versions / CI / CD pipelines can then do so and have a stable base to work on?

Here's a jenkins log we get now when trying to just build the vertx quickstart:

`<details>
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ demovertx18 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-version) @ demovertx18 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ demovertx18 ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ demovertx18 ---
[INFO] Executing: /bin/sh -c cd '/home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA
[INFO] Storing buildNumber: 26f93b09307a8e916fe47976e422542a04d9d27e at timestamp: 1491840225641
[INFO] Storing buildScmBranch: jstrachan/demovertx18/master-1.0.1
[INFO] 
[INFO] --- vertx-maven-plugin:1.0.6:initialize (vmp) @ demovertx18 ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ demovertx18 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- fabric8-maven-plugin:3.2.28:resource (fmp) @ demovertx18 ---
[INFO] F8: Running in OpenShift mode
[INFO] F8: Using docker image name of namespace: jastrachan-jenkins
[INFO] F8: Running generator vertx
[INFO] F8: vertx: Using Docker image fabric8/java-alpine-openjdk8-jdk:1.2 as base / builder
[INFO] F8: Using resource templates from /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/src/main/fabric8
[INFO] F8: fmp-controller: Adding a default Deployment
[INFO] F8: fmp-service: Adding a default Service with ports [8080]
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ demovertx18 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ demovertx18 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ demovertx18 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ demovertx18 ---
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ demovertx18 ---
[INFO] Building jar: /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/demovertx18-1.0.1.jar
[INFO] 
[INFO] --- vertx-maven-plugin:1.0.6:package (vmp) @ demovertx18 ---
[INFO] Executing: /bin/sh -c cd '/home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA' && 'git' 'whatchanged' '--until=2017-04-10 16:03:55 +0000' '--date=iso' '--' '/home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA'
[INFO] Working directory: /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA
[INFO] 
[INFO] --- fabric8-maven-plugin:3.2.28:build (fmp) @ demovertx18 ---
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] F8: Running generator vertx
[INFO] F8: vertx: Using Docker image fabric8/s2i-java:2.0 as base / builder
[INFO] Copying files to /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/docker/demovertx18/1.0.1/build/maven
[INFO] Building tar: /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/docker/demovertx18/1.0.1/tmp/docker-build.tar
[INFO] F8: [demovertx18:1.0.1] "vertx": Created docker source tar /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/docker/demovertx18/1.0.1/tmp/docker-build.tar
[INFO] F8: Creating BuildServiceConfig demovertx18-s2i for Source build
[INFO] F8: Creating ImageStream demovertx18
[INFO] F8: Starting Build demovertx18-s2i
[INFO] F8: Waiting for build demovertx18-s2i-1 to complete...
[INFO] F8: Receiving source from STDIN as archive ...
[INFO] F8: Pulling image "fabric8/s2i-java:2.0" ...
[INFO] WebSocket successfully opened
[INFO] F8: Pulling image "fabric8/s2i-java:2.0" ...
[INFO] F8: ==================================================================
[INFO] F8: Starting S2I Java Build .....
[INFO] F8: S2I binary build from fabric8-maven-plugin detected
[INFO] F8: Copying binaries from /tmp/src/maven to /deployments ...
[INFO] F8: ... done
[INFO] F8: 
[INFO] F8: Pushing image 172.30.215.46:5000/jastrachan-jenkins/demovertx18:1.0.1 ...
[INFO] F8: Pushed 0/23 layers, 0% complete
[INFO] F8: Pushed 1/23 layers, 4% complete
[INFO] F8: Build demovertx18-s2i-1 Complete
[INFO] WebSocket close received. code: 1000, reason: 
[WARNING] Ignoring onClose for already closed/closing websocket
[INFO] F8: Found tag on ImageStream demovertx18 tag: sha256:51b7db2c8dde999e1ebac82677783d192ffb654e26993f344b91a64a5f34feb6
[INFO] F8: ImageStream demovertx18 written to /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/demovertx18-is.yml
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (default) @ demovertx18 ---
[INFO] Failsafe report directory: /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.openshift.booster.OpenShiftIT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
application deployed, 4 object(s) created.
Apr 10, 2017 4:04:42 PM org.codehaus.groovy.runtime.m12n.SimpleExtensionModule getMetaMethods
WARNING: Module [demovertx18] - Unable to load extension class [class io.vertx.groovy.ext.web.handler.OAuth2AuthHandler_GroovyExtension] due to [io/vertx/ext/auth/oauth2/OAuth2Auth]. Maybe this module is not supported by your JVM version.
Apr 10, 2017 4:04:42 PM org.codehaus.groovy.runtime.m12n.SimpleExtensionModule getMetaMethods
WARNING: Module [io.vertx.ext.web.handler.VirtualHostHandler-module] - Unable to load extension class [class io.vertx.groovy.ext.web.handler.OAuth2AuthHandler_GroovyExtension] due to [io/vertx/ext/auth/oauth2/OAuth2Auth]. Maybe this module is not supported by your JVM version.
Route url: http://demovertx18-jastrachan-jenkins.d800.free-int.openshiftapps.com
sh-4.2$ exit
exit
Deleting application
Tests run: 3, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 341.224 sec <<< FAILURE! - in io.openshift.booster.OpenShiftIT
testBThatWeServeAsExpected(io.openshift.booster.OpenShiftIT)  Time elapsed: 1.149 sec  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
XML path content doesn't match.
Expected: Hello, World from Kubernetes ConfigMap !
  Actual: null
  /*!
   * Bootstrap v3.3.5 (http://getbootstrap.com)
   * Copyright 2011-2015 Twitter, Inc.
   * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
   */
  /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
  html {
    font-family: sans-serif;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
  }
  body {
    margin: 0;
  }
  h1 {
    font-size: 1.7em;
    font-weight: 400;
    line-height: 1.3;
    margin: 0.68em 0;
  }
  * {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }
  *:before,
  *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }
  html {
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  }
  body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    line-height: 1.66666667;
    font-size: 13px;
    color: #333333;
    background-color: #ffffff;
    margin: 2em 1em;
  }
  p {
    margin: 0 0 10px;
    font-size: 13px;
  }
  .alert.alert-info {
    padding: 15px;
    margin-bottom: 20px;
    border: 1px solid transparent;
    background-color: #f5f5f5;
    border-color: #8b8d8f;
    color: #363636;
    margin-top: 30px;
  }
  .alert p {
    padding-left: 35px;
  }
  a {
    color: #0088ce;
  }

  ul {
    position: relative;
    padding-left: 51px;
  }
  p.info {
    position: relative;
    font-size: 15px;
    margin-bottom: 10px;
  }
  p.info:before, p.info:after {
    content: "";
    position: absolute;
    top: 9%;
    left: 0;
  }
  p.info:before {
    content: "i";
    left: 3px;
    width: 20px;
    height: 20px;
    font-family: serif;
    font-size: 15px;
    font-weight: bold;
    line-height: 21px;
    text-align: center;
    color: #fff;
    background: #4d5258;
    border-radius: 16px;
  }

  @media (min-width: 768px) {
    body {
      margin: 4em 3em;
    }
    h1 {
      font-size: 2.15em;}
  }

  Application is not availableThe application is currently not serving requests at this endpoint. It may not have been started or is still starting.
          Possible reasons you are seeing this page:
        The host doesn't exist.The host exists, but doesn't have a matching path.Route and path matches, but all pods are down.

	at io.openshift.booster.OpenShiftIT.testBThatWeServeAsExpected(OpenShiftIT.java:48)

testCThatWeCanReloadTheConfiguration(io.openshift.booster.OpenShiftIT)  Time elapsed: 300.19 sec  <<< ERROR!
com.jayway.awaitility.core.ConditionTimeoutException: Condition with io.openshift.booster.OpenShiftIT was not fulfilled within 5 minutes.
	at io.openshift.booster.OpenShiftIT.testCThatWeCanReloadTheConfiguration(OpenShiftIT.java:61)

Results :

Failed tests: 
  OpenShiftIT.testBThatWeServeAsExpected:48 1 expectation failed.
XML path content doesn't match.
Expected: Hello, World from Kubernetes ConfigMap !
  Actual: null
  /*!
   * Bootstrap v3.3.5 (http://getbootstrap.com)
   * Copyright 2011-2015 Twitter, Inc.
   * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
   */
  /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
  html {
    font-family: sans-serif;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
  }
  body {
    margin: 0;
  }
  h1 {
    font-size: 1.7em;
    font-weight: 400;
    line-height: 1.3;
    margin: 0.68em 0;
  }
  * {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }
  *:before,
  *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }
  html {
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  }
  body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    line-height: 1.66666667;
    font-size: 13px;
    color: #333333;
    background-color: #ffffff;
    margin: 2em 1em;
  }
  p {
    margin: 0 0 10px;
    font-size: 13px;
  }
  .alert.alert-info {
    padding: 15px;
    margin-bottom: 20px;
    border: 1px solid transparent;
    background-color: #f5f5f5;
    border-color: #8b8d8f;
    color: #363636;
    margin-top: 30px;
  }
  .alert p {
    padding-left: 35px;
  }
  a {
    color: #0088ce;
  }

  ul {
    position: relative;
    padding-left: 51px;
  }
  p.info {
    position: relative;
    font-size: 15px;
    margin-bottom: 10px;
  }
  p.info:before, p.info:after {
    content: "";
    position: absolute;
    top: 9%;
    left: 0;
  }
  p.info:before {
    content: "i";
    left: 3px;
    width: 20px;
    height: 20px;
    font-family: serif;
    font-size: 15px;
    font-weight: bold;
    line-height: 21px;
    text-align: center;
    color: #fff;
    background: #4d5258;
    border-radius: 16px;
  }

  @media (min-width: 768px) {
    body {
      margin: 4em 3em;
    }
    h1 {
      font-size: 2.15em;}
  }

  Application is not availableThe application is currently not serving requests at this endpoint. It may not have been started or is still starting.
          Possible reasons you are seeing this page:
        The host doesn't exist.The host exists, but doesn't have a matching path.Route and path matches, but all pods are down.

Tests in error: 
  OpenShiftIT.testCThatWeCanReloadTheConfiguration:61 ? ConditionTimeout Conditi...

Tests run: 3, Failures: 1, Errors: 1, Skipped: 0

[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ demovertx18 ---
[INFO] Failsafe report directory: /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:41 min
[INFO] Finished at: 2017-04-10T16:10:21+00:00
[INFO] Final Memory: 47M/473M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project demovertx18: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project demovertx18: There are test failures.

Please refer to /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/failsafe-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/jenkins/workspace/strachan_demovertx18_master-VFLHA4WH2L5RQZE2LZ46SB5VRHEPHXMH5KNXTVYJOJXNVIA365IA/target/failsafe-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:91)
	at org.apache.maven.plugin.failsafe.VerifyMojo.execute(VerifyMojo.java:202)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[Pipeline] }
</details>`

**Comment by ALRubinger** [comment]
The bigger issue is that the DevTools team needs to be relying upon a release for their dev, not our snapshots.  We cut our first train midweek.

Until then, @cescoffier would you mind addressing the specific issues raised here by @jstrachan ?

**Comment by ALRubinger** [comment]
@gastaldi To the comments above, please audit and ensure that when we do a release train the DevTools team will be able to rely on a locked version of either catalog or however they consume it so they don't see our snapshot changes between releases.

**Comment by ALRubinger** [comment]
@jstrachan:
  You're requesting a proper release rather than relying on SHAPSHOTs; totally valid.  We've had planned a regular release train starting midweek, but you're ahead of schedule.  We haven't been prepared for "production support" yet.  Because you've forked some work (the launchpad-backend) I'm still not 100% on which components we're developing are leaking through for you, and which are isolated.  I see here that the Booster repos are coming straight through so let's lock those down for you and give you a stable base.
  In the meantime, we're working on releasing you a stopgap.  When it's ready, I'll ping back here; please try it out and let us know if you need updates issued; I'd picked SHAs of the Boosters in an attempt to choosing working ones and some adjustments may be necessary.

**Comment by gastaldi** [comment]
I just released our launchpad-addon which uses our structure: http://central.maven.org/maven2/io/openshift/launchpad/launchpad-addon/2.0.0.Alpha1/launchpad-addon-2.0.0.Alpha1.

If you are using the furnace-maven-plugin, just remove the old obsidian addon and use this instead: 

````
      <addonId>io.openshift.launchpad:launchpad-addon,2.0.0.Alpha1</addonId>
````

Otherwise just update your pom.xml to depend on the new addon: 

````xml
<dependency>
    <groupId>io.openshift.launchpad</groupId>
    <artifactId>launchpad-addon</artifactId>
    <version>2.0.0.Alpha1</version>
</dependency>
````

Make sure to set the `LAUNCHPAD_BACKEND_CATALOG_GIT_REF` environment variable to `stopgap-release` to use the frozen version of our boosters:

````
   export LAUNCHPAD_BACKEND_CATALOG_GIT_REF=stopgap-release
````

**Comment by gastaldi** [comment]
@jstrachan can you update your backend and confirm that things work as expected?

**Comment by jstrachan** [comment]
@ALRubinger the component which broke is the `obsidian-addon`. As I've said to you many times now, we reuse that, we've not forked it. The only thing we forked is the WF Swarm project that runs forge-service and hosts the forge addons.

@gastaldi trying to upgrade now thanks

**Comment by jstrachan** [comment]
looks like all the commands have changed so I'll have to change our forge addon, the back end and the fabric8-ui too...

**Comment by jstrachan** [comment]
@gastaldi any idea what these exceptions mean when I try use this new version:
```
2017-04-11 09:07:00,335 SEVERE [org.obsidiantoaster.generator.rest.ObsidianResource] (ServerService Thread Pool -- 24) Error while warming up cache: java.lang.NullPointerException
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_ac082ea0-3e90-40b2-b399-8be58790ba90.initialize(CommandController_$$_javassist_ac082ea0-3e90-40b2-b399-8be58790ba90.java)
	at org.obsidiantoaster.generator.rest.ObsidianResource.getCommand(ObsidianResource.java:606)
	at org.obsidiantoaster.generator.rest.ObsidianResource.init(ObsidianResource.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:313)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:291)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:269)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:302)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:291)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:89)
	at org.obsidiantoaster.generator.ForgeInitializer.contextInitialized(ForgeInitializer.java:82)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:200)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:171)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:234)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

2017-04-11 09:07:00,382 INFO  [org.infinispan.cdi.embedded.InfinispanExtensionEmbedded] (io.fabric8.forge:fabric8-generator,1.0.0-SNAPSHOT) ISPN017003: Overriding default embedded configuration not found - adding default implementation
2017-04-11 09:07:00,394 INFO  [org.infinispan.cdi.embedded.InfinispanExtensionEmbedded] (io.fabric8.forge:fabric8-generator,1.0.0-SNAPSHOT) ISPN017004: Overriding default embedded cache manager not found - adding default implementation
2017-04-11 09:07:00,415 SEVERE [org.jboss.forge.furnace.impl.addons.AddonRunnable] (io.fabric8.forge:fabric8-generator,1.0.0-SNAPSHOT) Failed to start addon [io.fabric8.forge:fabric8-generator,1.0.0-SNAPSHOT] with classloader [ModuleClassLoader for Module "io.fabric8.forge.fabric8-generator:1.0.0-SNAPSHOT_0cf95908-0c9e-46f4-963e-3fe25b4d4422" from AddonModuleLoader]: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type List<ProjectType> with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private io.openshift.launchpad.ui.starter.NewStarterWizard.supportedTypes
  at io.openshift.launchpad.ui.starter.NewStarterWizard.supportedTypes(NewStarterWizard.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:362)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:137)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:158)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:501)
	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:487)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:462)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:454)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:737)
	at org.jboss.forge.furnace.container.cdi.lifecycle.WeldAddonLifecycleProvider.start(WeldAddonLifecycleProvider.java:78)
	at org.jboss.forge.furnace.impl.addons.AddonRunnable$2.call(AddonRunnable.java:92)
	at org.jboss.forge.furnace.impl.addons.AddonRunnable$2.call(AddonRunnable.java:86)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.impl.addons.AddonRunnable.run(AddonRunnable.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jstrachan** [comment]
FWIW I've disabled obsidian for now on devtools as it was blocking all our work on jenkins, pipelines & CD so for now we're using the upstream fabric8 quickstarts until we can figure out how to use obsidian again with our pipelines

**Comment by gastaldi** [comment]
Talking with @jstrachan atm. Seems like I forgot to specify the `<classifier>forge-addon</classifier>` in the <dependency> tag above

**Comment by jstrachan** [comment]
plus various other commits relating to version upgrades and command name changes... making progress though

**Comment by gastaldi** [comment]
@jstrachan Looks like the backend is working now? What else is missing to close this issue?

**Comment by jstrachan** [comment]
need the new branch to use for the working vertx quickstart; then I can test it out on DevTools. If that works then great, we're sorted - otherwise its probably better if I spin up separate issues

**Comment by gastaldi** [comment]
@jstrachan I updated the branch to the latest frozen working vertx-http quickstart . Can you give it a spin?

Make sure to use: 

   export LAUNCHPAD_BACKEND_CATALOG_GIT_REF=devtools-saas

**Comment by jstrachan** [comment]
@gastaldi OK I've managed to create a vertx booster all via DevTools console - thanks for your help!

I'll see how far the pipelines get & raise separate issues if we hit stuff
